using System.Collections.Generic;
using System.Linq;
using System.Management;
using System.Threading.Tasks;
using Win11Checker.Models;

namespace Win11Checker.Sources.Windows
{
	public class CPU
	{
		public static async Task<Models.CPU> GetCPUAsync()
		{
			SelectQuery selectQuery = new("Win32_Processor");
			ManagementObjectSearcher managementObjectSearcher = new(selectQuery);
			ManagementObjectCollection managementObjects = managementObjectSearcher.Get();
			var cpuName = string.Empty;
			var architecture = Architecture.x86;
			foreach (ManagementObject mo in managementObjects)
			{
				cpuName = mo["Name"].ToString();
				architecture = (Architecture)(ushort)mo["Architecture"];
			}
			return await Task.FromResult(lookup.First());
		}
		#region Lookup Table
		public static readonly List<Models.CPU> lookup = new()
		{
			new Models.CPU("Intel®", "Atom®", "x6200FE", true),
			new Models.CPU("Intel®", "Atom®", "x6211E", true),
			new Models.CPU("Intel®", "Atom®", "x6212RE", true),
			new Models.CPU("Intel®", "Atom®", "x6413E", true),
			new Models.CPU("Intel®", "Atom®", "x6414RE", true),
			new Models.CPU("Intel®", "Atom®", "x6425E", true),
			new Models.CPU("Intel®", "Atom®", "x6425RE", true),
			new Models.CPU("Intel®", "Atom®", "x6427FE", true),
			new Models.CPU("Intel®", "Celeron®", "G4900", true),
			new Models.CPU("Intel®", "Celeron®", "G4900T", true),
			new Models.CPU("Intel®", "Celeron®", "G4920", true),
			new Models.CPU("Intel®", "Celeron®", "G4930", true),
			new Models.CPU("Intel®", "Celeron®", "G4930E", true),
			new Models.CPU("Intel®", "Celeron®", "G4930T", true),
			new Models.CPU("Intel®", "Celeron®", "G4932E", true),
			new Models.CPU("Intel®", "Celeron®", "G4950", true),
			new Models.CPU("Intel®", "Celeron®", "J4005", true),
			new Models.CPU("Intel®", "Celeron®", "J4105", true),
			new Models.CPU("Intel®", "Celeron®", "J4115", true),
			new Models.CPU("Intel®", "Celeron®", "N4000", true),
			new Models.CPU("Intel®", "Celeron®", "N4100", true),
			new Models.CPU("Intel®", "Celeron®", "3867U", true),
			new Models.CPU("Intel®", "Celeron®", "4205U", true),
			new Models.CPU("Intel®", "Celeron®", "4305U", true),
			new Models.CPU("Intel®", "Celeron®", "4305UE", true),
			new Models.CPU("Intel®", "Celeron®", "J4025", true),
			new Models.CPU("Intel®", "Celeron®", "J4125", true),
			new Models.CPU("Intel®", "Celeron®", "N4020", true),
			new Models.CPU("Intel®", "Celeron®", "N4120", true),
			new Models.CPU("Intel®", "Celeron®", "5205U", true),
			new Models.CPU("Intel®", "Celeron®", "5305U", true),
			new Models.CPU("Intel®", "Celeron®", "G5900", true),
			new Models.CPU("Intel®", "Celeron®", "G5900E", true),
			new Models.CPU("Intel®", "Celeron®", "G5900T", true),
			new Models.CPU("Intel®", "Celeron®", "G5900TE", true),
			new Models.CPU("Intel®", "Celeron®", "G5905", true),
			new Models.CPU("Intel®", "Celeron®", "G5905T", true),
			new Models.CPU("Intel®", "Celeron®", "G5920", true),
			new Models.CPU("Intel®", "Celeron®", "G5925", true),
			new Models.CPU("Intel®", "Celeron®", "J6412", true),
			new Models.CPU("Intel®", "Celeron®", "J6413", true),
			new Models.CPU("Intel®", "Celeron®", "N6210", true),
			new Models.CPU("Intel®", "Celeron®", "N6211", true),
			new Models.CPU("Intel®", "Celeron®", "N4500", true),
			new Models.CPU("Intel®", "Celeron®", "N4505", true),
			new Models.CPU("Intel®", "Celeron®", "N5100", true),
			new Models.CPU("Intel®", "Celeron®", "N5105", true),
			new Models.CPU("Intel®", "Celeron®", "6305", true),
			new Models.CPU("Intel®", "Celeron®", "6305E", true),
			new Models.CPU("Intel®", "Core™", "i5-10210Y", true),
			new Models.CPU("Intel®", "Core™", "i5-10310Y", true),
			new Models.CPU("Intel®", "Core™", "i5-8200Y", true),
			new Models.CPU("Intel®", "Core™", "i5-8210Y", true),
			new Models.CPU("Intel®", "Core™", "i5-8310Y", true),
			new Models.CPU("Intel®", "Core™", "i7-10510Y", true),
			new Models.CPU("Intel®", "Core™", "i7-8500Y", true),
			new Models.CPU("Intel®", "Core™", "m3-8100Y", true),
			new Models.CPU("Intel®", "Core™", "i3-8100", true),
			new Models.CPU("Intel®", "Core™", "i3-8100B", true),
			new Models.CPU("Intel®", "Core™", "i3-8100H", true),
			new Models.CPU("Intel®", "Core™", "i3-8100T", true),
			new Models.CPU("Intel®", "Core™", "i3-8109U", true),
			new Models.CPU("Intel®", "Core™", "i3-8140U", true),
			new Models.CPU("Intel®", "Core™", "i3-8300", true),
			new Models.CPU("Intel®", "Core™", "i3-8300T", true),
			new Models.CPU("Intel®", "Core™", "i3-8350K", true),
			new Models.CPU("Intel®", "Core™", "i5+8400", true),
			new Models.CPU("Intel®", "Core™", "i5+8500", true),
			new Models.CPU("Intel®", "Core™", "i5-8257U", true),
			new Models.CPU("Intel®", "Core™", "i5-8259U", true),
			new Models.CPU("Intel®", "Core™", "i5-8260U", true),
			new Models.CPU("Intel®", "Core™", "i5-8269U", true),
			new Models.CPU("Intel®", "Core™", "i5-8279U", true),
			new Models.CPU("Intel®", "Core™", "i5-8300H", true),
			new Models.CPU("Intel®", "Core™", "i5-8400", true),
			new Models.CPU("Intel®", "Core™", "i5-8400B", true),
			new Models.CPU("Intel®", "Core™", "i5-8400H", true),
			new Models.CPU("Intel®", "Core™", "i5-8400T", true),
			new Models.CPU("Intel®", "Core™", "i5-8500", true),
			new Models.CPU("Intel®", "Core™", "i5-8500B", true),
			new Models.CPU("Intel®", "Core™", "i5-8500T", true),
			new Models.CPU("Intel®", "Core™", "i5-8600", true),
			new Models.CPU("Intel®", "Core™", "i5-8600K", true),
			new Models.CPU("Intel®", "Core™", "i5-8600T", true),
			new Models.CPU("Intel®", "Core™", "i7-8086K", true),
			new Models.CPU("Intel®", "Core™", "i7-8557U", true),
			new Models.CPU("Intel®", "Core™", "i7-8559U", true),
			new Models.CPU("Intel®", "Core™", "i7-8569U", true),
			new Models.CPU("Intel®", "Core™", "i7-8700", true),
			new Models.CPU("Intel®", "Core™", "i7-8700B", true),
			new Models.CPU("Intel®", "Core™", "i7-8700K", true),
			new Models.CPU("Intel®", "Core™", "i7-8700T", true),
			new Models.CPU("Intel®", "Core™", "i7-8750H", true),
			new Models.CPU("Intel®", "Core™", "i7-8850H", true),
			new Models.CPU("Intel®", "Core™", "i3-8130U", true),
			new Models.CPU("Intel®", "Core™", "i5-8250U", true),
			new Models.CPU("Intel®", "Core™", "i5-8350U", true),
			new Models.CPU("Intel®", "Core™", "i7-8550U", true),
			new Models.CPU("Intel®", "Core™", "i7-8650U", true),
			new Models.CPU("Intel®", "Core™", "i3-8145U", true),
			new Models.CPU("Intel®", "Core™", "i3-8145UE", true),
			new Models.CPU("Intel®", "Core™", "i5-8265U", true),
			new Models.CPU("Intel®", "Core™", "i5-8365U", true),
			new Models.CPU("Intel®", "Core™", "i5-8365UE", true),
			new Models.CPU("Intel®", "Core™", "i7-8565U", true),
			new Models.CPU("Intel®", "Core™", "i7-8665U", true),
			new Models.CPU("Intel®", "Core™", "i7-8665UE", true),
			new Models.CPU("Intel®", "Core™", "i3-9100", true),
			new Models.CPU("Intel®", "Core™", "i3-9100E", true),
			new Models.CPU("Intel®", "Core™", "i3-9100F", true),
			new Models.CPU("Intel®", "Core™", "i3-9100HL", true),
			new Models.CPU("Intel®", "Core™", "i3-9100T", true),
			new Models.CPU("Intel®", "Core™", "i3-9100TE", true),
			new Models.CPU("Intel®", "Core™", "i3-9300", true),
			new Models.CPU("Intel®", "Core™", "i3-9300T", true),
			new Models.CPU("Intel®", "Core™", "i3-9320", true),
			new Models.CPU("Intel®", "Core™", "i3-9350K", true),
			new Models.CPU("Intel®", "Core™", "i3-9350KF", true),
			new Models.CPU("Intel®", "Core™", "i5-9300H", true),
			new Models.CPU("Intel®", "Core™", "i5-9300HF", true),
			new Models.CPU("Intel®", "Core™", "i5-9400", true),
			new Models.CPU("Intel®", "Core™", "i5-9400F", true),
			new Models.CPU("Intel®", "Core™", "i5-9400H", true),
			new Models.CPU("Intel®", "Core™", "i5-9400T", true),
			new Models.CPU("Intel®", "Core™", "i5-9500", true),
			new Models.CPU("Intel®", "Core™", "i5-9500E", true),
			new Models.CPU("Intel®", "Core™", "i5-9500F", true),
			new Models.CPU("Intel®", "Core™", "i5-9500T", true),
			new Models.CPU("Intel®", "Core™", "i5-9500TE", true),
			new Models.CPU("Intel®", "Core™", "i5-9600", true),
			new Models.CPU("Intel®", "Core™", "i5-9600K", true),
			new Models.CPU("Intel®", "Core™", "i5-9600KF", true),
			new Models.CPU("Intel®", "Core™", "i5-9600T", true),
			new Models.CPU("Intel®", "Core™", "i7-9700", true),
			new Models.CPU("Intel®", "Core™", "i7-9700E", true),
			new Models.CPU("Intel®", "Core™", "i7-9700F", true),
			new Models.CPU("Intel®", "Core™", "i7-9700K", true),
			new Models.CPU("Intel®", "Core™", "i7-9700KF", true),
			new Models.CPU("Intel®", "Core™", "i7-9700T", true),
			new Models.CPU("Intel®", "Core™", "i7-9700TE", true),
			new Models.CPU("Intel®", "Core™", "i7-9750H", true),
			new Models.CPU("Intel®", "Core™", "i7-9750HF", true),
			new Models.CPU("Intel®", "Core™", "i7-9850H", true),
			new Models.CPU("Intel®", "Core™", "i7-9850HE", true),
			new Models.CPU("Intel®", "Core™", "i7-9850HL", true),
			new Models.CPU("Intel®", "Core™", "i9-8950HK", true),
			new Models.CPU("Intel®", "Core™", "i9-9880H", true),
			new Models.CPU("Intel®", "Core™", "i9-9900", true),
			new Models.CPU("Intel®", "Core™", "i9-9900K", true),
			new Models.CPU("Intel®", "Core™", "i9-9900KF", true),
			new Models.CPU("Intel®", "Core™", "i9-9900KS", true),
			new Models.CPU("Intel®", "Core™", "i9-9900T", true),
			new Models.CPU("Intel®", "Core™", "i9-9980HK", true),
			new Models.CPU("Intel®", "Core™", "i3-10100Y", true),
			new Models.CPU("Intel®", "Core™", "i3-10110Y", true),
			new Models.CPU("Intel®", "Core™", "i9-10900X", true),
			new Models.CPU("Intel®", "Core™", "i9-10920X", true),
			new Models.CPU("Intel®", "Core™", "i9-10940X", true),
			new Models.CPU("Intel®", "Core™", "i9-10980XE", true),
			new Models.CPU("Intel®", "Core™", "i3-10100", true),
			new Models.CPU("Intel®", "Core™", "i3-10100E", true),
			new Models.CPU("Intel®", "Core™", "i3-10100F", true),
			new Models.CPU("Intel®", "Core™", "i3-10100T", true),
			new Models.CPU("Intel®", "Core™", "i3-10100TE", true),
			new Models.CPU("Intel®", "Core™", "i3-10105", true),
			new Models.CPU("Intel®", "Core™", "i3-10105F", true),
			new Models.CPU("Intel®", "Core™", "i3-10105T", true),
			new Models.CPU("Intel®", "Core™", "i3-10110U", true),
			new Models.CPU("Intel®", "Core™", "i3-10300", true),
			new Models.CPU("Intel®", "Core™", "i3-10300T", true),
			new Models.CPU("Intel®", "Core™", "i3-10305", true),
			new Models.CPU("Intel®", "Core™", "i3-10305T", true),
			new Models.CPU("Intel®", "Core™", "i3-10320", true),
			new Models.CPU("Intel®", "Core™", "i3-10325", true),
			new Models.CPU("Intel®", "Core™", "i5-10200H", true),
			new Models.CPU("Intel®", "Core™", "i5-10210U", true),
			new Models.CPU("Intel®", "Core™", "i5-10300H", true),
			new Models.CPU("Intel®", "Core™", "i5-10310U", true),
			new Models.CPU("Intel®", "Core™", "i5-10400", true),
			new Models.CPU("Intel®", "Core™", "i5-10400F", true),
			new Models.CPU("Intel®", "Core™", "i5-10400H", true),
			new Models.CPU("Intel®", "Core™", "i5-10400T", true),
			new Models.CPU("Intel®", "Core™", "i5-10500", true),
			new Models.CPU("Intel®", "Core™", "i5-10500E", true),
			new Models.CPU("Intel®", "Core™", "i5-10500H", true),
			new Models.CPU("Intel®", "Core™", "i5-10500T", true),
			new Models.CPU("Intel®", "Core™", "i5-10500TE", true),
			new Models.CPU("Intel®", "Core™", "i5-10600", true),
			new Models.CPU("Intel®", "Core™", "i5-10600K", true),
			new Models.CPU("Intel®", "Core™", "i5-10600KF", true),
			new Models.CPU("Intel®", "Core™", "i5-10600T", true),
			new Models.CPU("Intel®", "Core™", "i7-10510U", true),
			new Models.CPU("Intel®", "Core™", "i7-10610U", true),
			new Models.CPU("Intel®", "Core™", "i7-10700", true),
			new Models.CPU("Intel®", "Core™", "i7-10700E", true),
			new Models.CPU("Intel®", "Core™", "i7-10700F", true),
			new Models.CPU("Intel®", "Core™", "i7-10700K", true),
			new Models.CPU("Intel®", "Core™", "i7-10700KF", true),
			new Models.CPU("Intel®", "Core™", "i7-10700T", true),
			new Models.CPU("Intel®", "Core™", "i7-10700TE", true),
			new Models.CPU("Intel®", "Core™", "i7-10710U", true),
			new Models.CPU("Intel®", "Core™", "i7-10750H", true),
			new Models.CPU("Intel®", "Core™", "i7-10810U", true),
			new Models.CPU("Intel®", "Core™", "i7-10850H", true),
			new Models.CPU("Intel®", "Core™", "i7-10870H", true),
			new Models.CPU("Intel®", "Core™", "i7-10875H", true),
			new Models.CPU("Intel®", "Core™", "i9-10850K", true),
			new Models.CPU("Intel®", "Core™", "i9-10885H", true),
			new Models.CPU("Intel®", "Core™", "i9-10900", true),
			new Models.CPU("Intel®", "Core™", "i9-10900E", true),
			new Models.CPU("Intel®", "Core™", "i9-10900F", true),
			new Models.CPU("Intel®", "Core™", "i9-10900K", true),
			new Models.CPU("Intel®", "Core™", "i9-10900KF", true),
			new Models.CPU("Intel®", "Core™", "i9-10900T", true),
			new Models.CPU("Intel®", "Core™", "i9-10900TE", true),
			new Models.CPU("Intel®", "Core™", "i9-10980HK", true),
			new Models.CPU("Intel®", "Core™", "i3-1000G1", true),
			new Models.CPU("Intel®", "Core™", "i3-1000G4", true),
			new Models.CPU("Intel®", "Core™", "i3-1005G1", true),
			new Models.CPU("Intel®", "Core™", "i5-1030G4", true),
			new Models.CPU("Intel®", "Core™", "i5-1030G7", true),
			new Models.CPU("Intel®", "Core™", "i5-1035G1", true),
			new Models.CPU("Intel®", "Core™", "i5-1035G4", true),
			new Models.CPU("Intel®", "Core™", "i5-1035G7", true),
			new Models.CPU("Intel®", "Core™", "i5-1038NG7", true),
			new Models.CPU("Intel®", "Core™", "i7-1060G7", true),
			new Models.CPU("Intel®", "Core™", "i7-1065G7", true),
			new Models.CPU("Intel®", "Core™", "i7-1068NG7", true),
			new Models.CPU("Intel®", "Core™", "i3-L13G4", true),
			new Models.CPU("Intel®", "Core™", "i5-L16G7", true),
			new Models.CPU("Intel®", "Core™", "i5-11400", true),
			new Models.CPU("Intel®", "Core™", "i5-11400F", true),
			new Models.CPU("Intel®", "Core™", "i5-11400T", true),
			new Models.CPU("Intel®", "Core™", "i5-11500", true),
			new Models.CPU("Intel®", "Core™", "i5-11500T", true),
			new Models.CPU("Intel®", "Core™", "i5-11600", true),
			new Models.CPU("Intel®", "Core™", "i5-11600K", true),
			new Models.CPU("Intel®", "Core™", "i5-11600KF", true),
			new Models.CPU("Intel®", "Core™", "i5-11600T", true),
			new Models.CPU("Intel®", "Core™", "i7-11700", true),
			new Models.CPU("Intel®", "Core™", "i7-11700F", true),
			new Models.CPU("Intel®", "Core™", "i7-11700K", true),
			new Models.CPU("Intel®", "Core™", "i7-11700KF", true),
			new Models.CPU("Intel®", "Core™", "i7-11700T", true),
			new Models.CPU("Intel®", "Core™", "i9-11900", true),
			new Models.CPU("Intel®", "Core™", "i9-11900F", true),
			new Models.CPU("Intel®", "Core™", "i9-11900K", true),
			new Models.CPU("Intel®", "Core™", "i9-11900KF", true),
			new Models.CPU("Intel®", "Core™", "i9-11900T", true),
			new Models.CPU("Intel®", "Core™", "i3-1110G4", true),
			new Models.CPU("Intel®", "Core™", "i3-1115G4", true),
			new Models.CPU("Intel®", "Core™", "i3-1115G4E", true),
			new Models.CPU("Intel®", "Core™", "i3-1115GRE", true),
			new Models.CPU("Intel®", "Core™", "i3-1120G4", true),
			new Models.CPU("Intel®", "Core™", "i3-1125G4", true),
			new Models.CPU("Intel®", "Core™", "i5-11300H", true),
			new Models.CPU("Intel®", "Core™", "i5-1130G7", true),
			new Models.CPU("Intel®", "Core™", "i5-1135G7", true),
			new Models.CPU("Intel®", "Core™", "i5-1135G7", true),
			new Models.CPU("Intel®", "Core™", "i5-1140G7", true),
			new Models.CPU("Intel®", "Core™", "i5-1145G7", true),
			new Models.CPU("Intel®", "Core™", "i5-1145G7E", true),
			new Models.CPU("Intel®", "Core™", "i5-1145GRE", true),
			new Models.CPU("Intel®", "Core™", "i7-11370H", true),
			new Models.CPU("Intel®", "Core™", "i7-11375H", true),
			new Models.CPU("Intel®", "Core™", "i7-1160G7", true),
			new Models.CPU("Intel®", "Core™", "i7-1165G7", true),
			new Models.CPU("Intel®", "Core™", "i7-1165G7", true),
			new Models.CPU("Intel®", "Core™", "i7-1180G7", true),
			new Models.CPU("Intel®", "Core™", "i7-1185G7", true),
			new Models.CPU("Intel®", "Core™", "i7-1185G7E", true),
			new Models.CPU("Intel®", "Core™", "i7-1185GRE", true),
			new Models.CPU("Intel®", "Pentium®", "Gold 4425Y", true),
			new Models.CPU("Intel®", "Pentium®", "Gold 6500Y", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G5400", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G5400T", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G5420", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G5420T", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G5500", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G5500T", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G5600", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G5600T", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G5620", true),
			new Models.CPU("Intel®", "Pentium®", "Silver J5005", true),
			new Models.CPU("Intel®", "Pentium®", "Silver N5000", true),
			new Models.CPU("Intel®", "Pentium®", "Gold 4417U", true),
			new Models.CPU("Intel®", "Pentium®", "Gold 5405U", true),
			new Models.CPU("Intel®", "Pentium®", "Silver J5040", true),
			new Models.CPU("Intel®", "Pentium®", "Silver N5030", true),
			new Models.CPU("Intel®", "Pentium®", "Gold 6405U", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G6400", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G6400E", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G6400T", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G6400TE", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G6405", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G6405T", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G6500", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G6500T", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G6505", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G6505T", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G6600", true),
			new Models.CPU("Intel®", "Pentium®", "Gold G6605", true),
			new Models.CPU("Intel®", "Pentium®", "6805", true),
			new Models.CPU("Intel®", "Pentium®", "J6426", true),
			new Models.CPU("Intel®", "Pentium®", "N6415", true),
			new Models.CPU("Intel®", "Pentium®", "Silver N6000", true),
			new Models.CPU("Intel®", "Pentium®", "Silver N6005", true),
			new Models.CPU("Intel®", "Pentium®", "Gold 7505", true),
			new Models.CPU("Intel®", "Xeon®", "Bronze 3104", true),
			new Models.CPU("Intel®", "Xeon®", "Bronze 3106", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5115", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5118", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5119T", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5120", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5120T", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5122", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6126", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6126F", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6126T", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6128", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6130", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6130F", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6130T", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6132", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6134", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6136", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6138", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6138F", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6138P", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6138T", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6140", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6142", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6142F", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6144", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6146", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6148", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6148F", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6150", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6152", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6154", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8153", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8156", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8158", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8160", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8160F", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8160T", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8164", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8168", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8170", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8176", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8176F", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8180", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4108", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4109T", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4110", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4112", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4114", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4114T", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4116", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4116T", true),
			new Models.CPU("Intel®", "Xeon®", "E-2124", true),
			new Models.CPU("Intel®", "Xeon®", "E-2124G", true),
			new Models.CPU("Intel®", "Xeon®", "E-2126G", true),
			new Models.CPU("Intel®", "Xeon®", "E-2134", true),
			new Models.CPU("Intel®", "Xeon®", "E-2136", true),
			new Models.CPU("Intel®", "Xeon®", "E-2144G", true),
			new Models.CPU("Intel®", "Xeon®", "E-2146G", true),
			new Models.CPU("Intel®", "Xeon®", "E-2174G", true),
			new Models.CPU("Intel®", "Xeon®", "E-2176G", true),
			new Models.CPU("Intel®", "Xeon®", "E-2176M", true),
			new Models.CPU("Intel®", "Xeon®", "E-2186G", true),
			new Models.CPU("Intel®", "Xeon®", "E-2186M", true),
			new Models.CPU("Intel®", "Xeon®", "E-2224", true),
			new Models.CPU("Intel®", "Xeon®", "E-2224G", true),
			new Models.CPU("Intel®", "Xeon®", "E-2226G", true),
			new Models.CPU("Intel®", "Xeon®", "E-2226GE", true),
			new Models.CPU("Intel®", "Xeon®", "E-2234", true),
			new Models.CPU("Intel®", "Xeon®", "E-2236", true),
			new Models.CPU("Intel®", "Xeon®", "E-2244G", true),
			new Models.CPU("Intel®", "Xeon®", "E-2246G", true),
			new Models.CPU("Intel®", "Xeon®", "E-2254ME", true),
			new Models.CPU("Intel®", "Xeon®", "E-2254ML", true),
			new Models.CPU("Intel®", "Xeon®", "E-2274G", true),
			new Models.CPU("Intel®", "Xeon®", "E-2276G", true),
			new Models.CPU("Intel®", "Xeon®", "E-2276M", true),
			new Models.CPU("Intel®", "Xeon®", "E-2276ME", true),
			new Models.CPU("Intel®", "Xeon®", "E-2276ML", true),
			new Models.CPU("Intel®", "Xeon®", "E-2278G", true),
			new Models.CPU("Intel®", "Xeon®", "E-2278GE", true),
			new Models.CPU("Intel®", "Xeon®", "E-2278GEL", true),
			new Models.CPU("Intel®", "Xeon®", "E-2286G", true),
			new Models.CPU("Intel®", "Xeon®", "E-2286M", true),
			new Models.CPU("Intel®", "Xeon®", "E-2288G", true),
			new Models.CPU("Intel®", "Xeon®", "Bronze 3204", true),
			new Models.CPU("Intel®", "Xeon®", "Bronze 3206R", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5215", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5215L", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5217", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5218B", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5218N", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5218R", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5218T", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5220", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5220R", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5220S", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5220T", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5222", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6208U", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6209U", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6210U", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6212U", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6222V", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6226", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6226R", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6230", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6230N", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6230R", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6230T", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6238", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6238L", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6238T", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6240", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6240L", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6240R", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6240Y", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6242", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6242R", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6244", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6246R", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6248", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6248R", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6250", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6250L", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6252", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6252N", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6254", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6256", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6258R", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6262V", true),
			new Models.CPU("Intel®", "Xeon®", "Gold Gold 5218", true),
			new Models.CPU("Intel®", "Xeon®", "Gold Gold 6238R", true),
			new Models.CPU("Intel®", "Xeon®", "Gold6246", true),
			new Models.CPU("Intel®", "Xeon®", "Goldv 6234", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8253", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8256", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8260", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8260L", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8260Y", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8268", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8270", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8276", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8276L", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8280", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8280L", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 9221", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 9222", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 9242", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 9282", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4208", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4209T", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4210", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4210R", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4210T", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4214", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4214R", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4214Y", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4215", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4215R", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4216", true),
			new Models.CPU("Intel®", "Xeon®", "W-2223", true),
			new Models.CPU("Intel®", "Xeon®", "W-2225", true),
			new Models.CPU("Intel®", "Xeon®", "W-2235", true),
			new Models.CPU("Intel®", "Xeon®", "W-2245", true),
			new Models.CPU("Intel®", "Xeon®", "W-2255", true),
			new Models.CPU("Intel®", "Xeon®", "W-2265", true),
			new Models.CPU("Intel®", "Xeon®", "W-2275", true),
			new Models.CPU("Intel®", "Xeon®", "W-2295", true),
			new Models.CPU("Intel®", "Xeon®", "W-3223", true),
			new Models.CPU("Intel®", "Xeon®", "W-3225", true),
			new Models.CPU("Intel®", "Xeon®", "W-3235", true),
			new Models.CPU("Intel®", "Xeon®", "W-3245", true),
			new Models.CPU("Intel®", "Xeon®", "W-3245M", true),
			new Models.CPU("Intel®", "Xeon®", "W-3265", true),
			new Models.CPU("Intel®", "Xeon®", "W-3265M", true),
			new Models.CPU("Intel®", "Xeon®", "W-3275", true),
			new Models.CPU("Intel®", "Xeon®", "W-3275M", true),
			new Models.CPU("Intel®", "Xeon®", "W-10855M", true),
			new Models.CPU("Intel®", "Xeon®", "W-10885M", true),
			new Models.CPU("Intel®", "Xeon®", "W-1250", true),
			new Models.CPU("Intel®", "Xeon®", "W-1250E", true),
			new Models.CPU("Intel®", "Xeon®", "W-1250P", true),
			new Models.CPU("Intel®", "Xeon®", "W-1250TE", true),
			new Models.CPU("Intel®", "Xeon®", "W-1270", true),
			new Models.CPU("Intel®", "Xeon®", "W-1270E", true),
			new Models.CPU("Intel®", "Xeon®", "W-1270P", true),
			new Models.CPU("Intel®", "Xeon®", "W-1270TE", true),
			new Models.CPU("Intel®", "Xeon®", "W-1290", true),
			new Models.CPU("Intel®", "Xeon®", "W-1290E", true),
			new Models.CPU("Intel®", "Xeon®", "W-1290P", true),
			new Models.CPU("Intel®", "Xeon®", "W-1290T", true),
			new Models.CPU("Intel®", "Xeon®", "W-1290TE", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5315Y", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5317", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5318N", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5318S", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5320", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 5320T", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6312U", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6314U", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6326", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6330", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6330N", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6334", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6336Y", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6338", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6338N", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6338T", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6342", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6346", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6348", true),
			new Models.CPU("Intel®", "Xeon®", "Gold 6354", true),
			new Models.CPU("Intel®", "Xeon®", "Gold Gold 5318Y", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8351N", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8352S", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8352V", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8352Y", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8358", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8358P", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8360Y", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8368", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8368Q", true),
			new Models.CPU("Intel®", "Xeon®", "Platinum 8380", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4309Y", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4310", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4310T", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4314", true),
			new Models.CPU("Intel®", "Xeon®", "Silver 4316", true),
			new Models.CPU("AMD", "AMD", "3015e", true),
			new Models.CPU("AMD", "AMD", "3020e", true),
			new Models.CPU("AMD", "Athlon™", "Gold 3150C", true),
			new Models.CPU("AMD", "Athlon™", "Gold 3150U", true),
			new Models.CPU("AMD", "Athlon™", "Silver 3050C", true),
			new Models.CPU("AMD", "Athlon™", "Silver 3050e", true),
			new Models.CPU("AMD", "Athlon™", "Silver 3050U", true),
			new Models.CPU("AMD", "Athlon™", "3000G", true),
			new Models.CPU("AMD", "Athlon™", "300GE", true),
			new Models.CPU("AMD", "Athlon™", "300U", true),
			new Models.CPU("AMD", "Athlon™", "320GE", true),
			new Models.CPU("AMD", "Athlon™", "Gold 3150G", true),
			new Models.CPU("AMD", "Athlon™", "Gold 3150GE", true),
			new Models.CPU("AMD", "Athlon™", "Silver 3050GE", true),
			new Models.CPU("AMD", "EPYC™", "7232P", true),
			new Models.CPU("AMD", "EPYC™", "7252", true),
			new Models.CPU("AMD", "EPYC™", "7262", true),
			new Models.CPU("AMD", "EPYC™", "7272", true),
			new Models.CPU("AMD", "EPYC™", "7282", true),
			new Models.CPU("AMD", "EPYC™", "7302", true),
			new Models.CPU("AMD", "EPYC™", "7302P", true),
			new Models.CPU("AMD", "EPYC™", "7352", true),
			new Models.CPU("AMD", "EPYC™", "7402", true),
			new Models.CPU("AMD", "EPYC™", "7402P", true),
			new Models.CPU("AMD", "EPYC™", "7452", true),
			new Models.CPU("AMD", "EPYC™", "7502", true),
			new Models.CPU("AMD", "EPYC™", "7502P", true),
			new Models.CPU("AMD", "EPYC™", "7532", true),
			new Models.CPU("AMD", "EPYC™", "7542", true),
			new Models.CPU("AMD", "EPYC™", "7552", true),
			new Models.CPU("AMD", "EPYC™", "7642", true),
			new Models.CPU("AMD", "EPYC™", "7662", true),
			new Models.CPU("AMD", "EPYC™", "7702", true),
			new Models.CPU("AMD", "EPYC™", "7702P", true),
			new Models.CPU("AMD", "EPYC™", "7742", true),
			new Models.CPU("AMD", "EPYC™", "7F32", true),
			new Models.CPU("AMD", "EPYC™", "7F52", true),
			new Models.CPU("AMD", "EPYC™", "7F72", true),
			new Models.CPU("AMD", "EPYC™", "7H12", true),
			new Models.CPU("AMD", "EPYC™", "72F3", true),
			new Models.CPU("AMD", "EPYC™", "7313", true),
			new Models.CPU("AMD", "EPYC™", "7313P", true),
			new Models.CPU("AMD", "EPYC™", "7343", true),
			new Models.CPU("AMD", "EPYC™", "73F3", true),
			new Models.CPU("AMD", "EPYC™", "7413", true),
			new Models.CPU("AMD", "EPYC™", "7443", true),
			new Models.CPU("AMD", "EPYC™", "7443P", true),
			new Models.CPU("AMD", "EPYC™", "7453", true),
			new Models.CPU("AMD", "EPYC™", "74F3", true),
			new Models.CPU("AMD", "EPYC™", "7513", true),
			new Models.CPU("AMD", "EPYC™", "7543", true),
			new Models.CPU("AMD", "EPYC™", "7543P", true),
			new Models.CPU("AMD", "EPYC™", "75F3", true),
			new Models.CPU("AMD", "EPYC™", "7643", true),
			new Models.CPU("AMD", "EPYC™", "7663", true),
			new Models.CPU("AMD", "EPYC™", "7713", true),
			new Models.CPU("AMD", "EPYC™", "7713P", true),
			new Models.CPU("AMD", "EPYC™", "7763", true),
			new Models.CPU("AMD", "Ryzen™ 3", "3250C", true),
			new Models.CPU("AMD", "Ryzen™ 3", "3250U", true),
			new Models.CPU("AMD", "Ryzen™ 3", "3200G with Radeon™ Vega 8 Graphics", true),
			new Models.CPU("AMD", "Ryzen™ 3", "3200GE", true),
			new Models.CPU("AMD", "Ryzen™ 3", "3200U", true),
			new Models.CPU("AMD", "Ryzen™ 3", "3350U", true),
			new Models.CPU("AMD", "Ryzen™ 3", "2300X", true),
			new Models.CPU("AMD", "Ryzen™ 3", "5300U", true),
			new Models.CPU("AMD", "Ryzen™ 3", "3100", true),
			new Models.CPU("AMD", "Ryzen™ 3", "3300U", true),
			new Models.CPU("AMD", "Ryzen™ 3", "4300G", true),
			new Models.CPU("AMD", "Ryzen™ 3", "4300GE", true),
			new Models.CPU("AMD", "Ryzen™ 3", "4300U", true),
			new Models.CPU("AMD", "Ryzen™ 3", "5400U", true),
			new Models.CPU("AMD", "Ryzen™ 3 PRO", "3200G", true),
			new Models.CPU("AMD", "Ryzen™ 3 PRO", "3200GE", true),
			new Models.CPU("AMD", "Ryzen™ 3 PRO", "3300U", true),
			new Models.CPU("AMD", "Ryzen™ 3 PRO", "4350G", true),
			new Models.CPU("AMD", "Ryzen™ 3 PRO", "4350GE", true),
			new Models.CPU("AMD", "Ryzen™ 3 PRO", "4450U", true),
			new Models.CPU("AMD", "Ryzen™ 3 PRO", "5450U", true),
			new Models.CPU("AMD", "Ryzen™ 5", "3400G with Radeon™ RX Vega 11 Graphics", true),
			new Models.CPU("AMD", "Ryzen™ 5", "3400GE", true),
			new Models.CPU("AMD", "Ryzen™ 5", "3450U", true),
			new Models.CPU("AMD", "Ryzen™ 5", "3500C", true),
			new Models.CPU("AMD", "Ryzen™ 5", "3500U", true),
			new Models.CPU("AMD", "Ryzen™ 5", "3550H", true),
			new Models.CPU("AMD", "Ryzen™ 5", "3580U Microsoft Surface® Edition", true),
			new Models.CPU("AMD", "Ryzen™ 5", "2500X", true),
			new Models.CPU("AMD", "Ryzen™ 5", "2600", true),
			new Models.CPU("AMD", "Ryzen™ 5", "2600E", true),
			new Models.CPU("AMD", "Ryzen™ 5", "2600X", true),
			new Models.CPU("AMD", "Ryzen™ 5", "5500U", true),
			new Models.CPU("AMD", "Ryzen™ 5", "3500 Processor", true),
			new Models.CPU("AMD", "Ryzen™ 5", "3600", true),
			new Models.CPU("AMD", "Ryzen™ 5", "3600X", true),
			new Models.CPU("AMD", "Ryzen™ 5", "3600XT", true),
			new Models.CPU("AMD", "Ryzen™ 5", "4600G", true),
			new Models.CPU("AMD", "Ryzen™ 5", "4500U", true),
			new Models.CPU("AMD", "Ryzen™ 5", "4600GE", true),
			new Models.CPU("AMD", "Ryzen™ 5", "4600H", true),
			new Models.CPU("AMD", "Ryzen™ 5", "4600U", true),
			new Models.CPU("AMD", "Ryzen™ 5", "5600H", true),
			new Models.CPU("AMD", "Ryzen™ 5", "5600HS", true),
			new Models.CPU("AMD", "Ryzen™ 5", "5600U", true),
			new Models.CPU("AMD", "Ryzen™ 5", "5600X", true),
			new Models.CPU("AMD", "Ryzen™ 5 PRO", "3400G", true),
			new Models.CPU("AMD", "Ryzen™ 5 PRO", "3400GE", true),
			new Models.CPU("AMD", "Ryzen™ 5 PRO", "3500U", true),
			new Models.CPU("AMD", "Ryzen™ 5 PRO", "2600", true),
			new Models.CPU("AMD", "Ryzen™ 5 PRO", "3600", true),
			new Models.CPU("AMD", "Ryzen™ 5 PRO", "4650G", true),
			new Models.CPU("AMD", "Ryzen™ 5 PRO", "4650GE", true),
			new Models.CPU("AMD", "Ryzen™ 5 PRO", "4650U", true),
			new Models.CPU("AMD", "Ryzen™ 5 PRO", "5650U", true),
			new Models.CPU("AMD", "Ryzen™ 7", "3700C", true),
			new Models.CPU("AMD", "Ryzen™ 7", "3700U", true),
			new Models.CPU("AMD", "Ryzen™ 7", "3750H", true),
			new Models.CPU("AMD", "Ryzen™ 7", "3780U Microsoft Surface® Edition", true),
			new Models.CPU("AMD", "Ryzen™ 7", "2700", true),
			new Models.CPU("AMD", "Ryzen™ 7", "2700E Processor", true),
			new Models.CPU("AMD", "Ryzen™ 7", "2700X", true),
			new Models.CPU("AMD", "Ryzen™ 7", "5700U", true),
			new Models.CPU("AMD", "Ryzen™ 7", "3700X", true),
			new Models.CPU("AMD", "Ryzen™ 7", "3800X", true),
			new Models.CPU("AMD", "Ryzen™ 7", "3800XT", true),
			new Models.CPU("AMD", "Ryzen™ 7", "4700G", true),
			new Models.CPU("AMD", "Ryzen™ 7", "4700GE", true),
			new Models.CPU("AMD", "Ryzen™ 7", "4700U", true),
			new Models.CPU("AMD", "Ryzen™ 7", "4800H", true),
			new Models.CPU("AMD", "Ryzen™ 7", "4800HS", true),
			new Models.CPU("AMD", "Ryzen™ 7", "4800U", true),
			new Models.CPU("AMD", "Ryzen™ 7", "5800H", true),
			new Models.CPU("AMD", "Ryzen™ 7", "5800HS", true),
			new Models.CPU("AMD", "Ryzen™ 7", "5800U", true),
			new Models.CPU("AMD", "Ryzen™ 7", "5800", true),
			new Models.CPU("AMD", "Ryzen™ 7", "5800X", true),
			new Models.CPU("AMD", "Ryzen™ 7 PRO", "3700U", true),
			new Models.CPU("AMD", "Ryzen™ 7 PRO", "2700", true),
			new Models.CPU("AMD", "Ryzen™ 7 PRO", "2700X", true),
			new Models.CPU("AMD", "Ryzen™ 7 PRO", "4750G", true),
			new Models.CPU("AMD", "Ryzen™ 7 PRO", "4750GE", true),
			new Models.CPU("AMD", "Ryzen™ 7 PRO", "4750U", true),
			new Models.CPU("AMD", "Ryzen™ 7 PRO", "5850U", true),
			new Models.CPU("AMD", "Ryzen™ 9", "3900 Processor", true),
			new Models.CPU("AMD", "Ryzen™ 9", "3900X", true),
			new Models.CPU("AMD", "Ryzen™ 9", "3900XT", true),
			new Models.CPU("AMD", "Ryzen™ 9", "3950X", true),
			new Models.CPU("AMD", "Ryzen™ 9", "4900H", true),
			new Models.CPU("AMD", "Ryzen™ 9", "4900HS", true),
			new Models.CPU("AMD", "Ryzen™ 9", "5900HS", true),
			new Models.CPU("AMD", "Ryzen™ 9", "5900HX", true),
			new Models.CPU("AMD", "Ryzen™ 9", "5980HS", true),
			new Models.CPU("AMD", "Ryzen™ 9", "5980HX", true),
			new Models.CPU("AMD", "Ryzen™ 9", "5900", true),
			new Models.CPU("AMD", "Ryzen™ 9", "5900X", true),
			new Models.CPU("AMD", "Ryzen™ 9", "5950X", true),
			new Models.CPU("AMD", "Ryzen™ 9 PRO", "3900", true),
			new Models.CPU("AMD", "Ryzen™ Threadripper™", "2920X", true),
			new Models.CPU("AMD", "Ryzen™ Threadripper™", "2950X", true),
			new Models.CPU("AMD", "Ryzen™ Threadripper™", "2970WX", true),
			new Models.CPU("AMD", "Ryzen™ Threadripper™", "2990WX", true),
			new Models.CPU("AMD", "Ryzen™ Threadripper™", "3960X", true),
			new Models.CPU("AMD", "Ryzen™ Threadripper™", "3970X", true),
			new Models.CPU("AMD", "Ryzen™ Threadripper™", "3990X", true),
			new Models.CPU("AMD", "Ryzen™ Threadripper™ PRO", "3945WX", true),
			new Models.CPU("AMD", "Ryzen™ Threadripper™ PRO", "3955WX", true),
			new Models.CPU("AMD", "Ryzen™ Threadripper™ PRO", "3975WX", true),
			new Models.CPU("AMD", "Ryzen™ Threadripper™ PRO", "3995WX", true),
			new Models.CPU("Qualcomm®", "Snapdragon™", "Snapdragon 850", true),
			new Models.CPU("Qualcomm®", "Snapdragon™", "Snapdragon 7c", true),
			new Models.CPU("Qualcomm®", "Snapdragon™", "Snapdragon 8c", true),
			new Models.CPU("Qualcomm®", "Snapdragon™", "Snapdragon 8cx", true),
			new Models.CPU("Qualcomm®", "Snapdragon™", "Snapdragon 8cx (Gen2)", true),
			new Models.CPU("Qualcomm®", "Snapdragon™", "Microsoft SQ1", true),
			new Models.CPU("Qualcomm®", "Snapdragon™", "Microsoft SQ2", true)
		};

		#endregion
	}

}
